from BST import Bst
t = Bst()
t.create(10)
t.create(5)
t.create(2)
t.create(7)
t.create(4)
t.create(3)
t.create(15)
t.create(20)
t.create(11)
t.create(12)
t.create(13)
t.create(14)
print('Inorder:',end = ' ')
t.inorder()
print('Preorder:',end = ' ')
t.preorder()
print('Postorder:',end = ' ')
t.postorder()
print('Heigth:',t.height(t.root))
print('Total Sum:',t.summ(t.root))
print('Even Sum:',t.Evensum(t.root))
print('Odd Sum:',t.Oddsum(t.root))
print('Difference Sum:',t.diff())
print('Balanced:',t.is_balance())
print('Leaf Nodes:',t.leaf_node_count())
print('Sum of Leaf Nodes:',t.leaf_node_sum())
print('Search Found:', t.Search(10))
print('Depth:', t.finddepth(2))
print('Top View:',*t.topviewbfs())
print('Left View:',*t.leftview())
print('Right View:',*t.rightview())
print('Bottom View:',*t.bottomviewbfs())