from Trie_data_structure import Trie
t = Trie()
t.insert('world')
t.insert('word')
#print(t.search('word'))
t.insert('words')
t.insert('apple')
t.insert('wood')
t.insert('bull')
t.insert('ball')
t.insert('accenture')
# print(t.words_starts_with('wor'))
print(t.max_len_word_starts_with(['w', 'a', 'b']))
print(t.lexicographically_max_len_word_starts_with(['w', 'a', 'b']))