# 1  def append(self, val)
# 2  def add_at_front(self, val)
# 3  def pop(self)
# 4  def delete_at_front(self)
# 5  def search(self, val)
# 6  def even_or_odd(self)
# 7  def is_palindrome(self)
# 8  def change(self)
# 9  def change_sides(self)
# 10 def print(self)
# 11 def print_reverse(self)
# 12 def length(self)
# 13 def is_balance(self)
# 14 def print_sum(self)
# 15 def prime_count(self)


from Double_Linked_List import List
l = List()
l.append(0)
l.append(1)
l.append(2)
l.append(3)
l.append(4)
l.append(5)
l.append(6)
l.append(7)
l.append(8)
l.append(9)
l.print()
l.print()
#l.print_reverse()
#print(l.even_or_odd())
#l.change()
#l.print()
#l.change_sides()
print('Absolute diff = ',l.print_sum())
print('Prime Count = ',l.prime_count())